# Generated by Django 4.2 on 2023-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_booking_property_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyeval',
            name='price',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=80),
        ),
    ]
