# Generated by Django 4.2.1 on 2023-05-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
