# Generated by Django 4.2 on 2023-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertyeval_price_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyeval',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyeval',
            name='minimum_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyeval',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyeval',
            name='reviews_per_month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
