# Generated by Django 4.2 on 2023-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyeval_available_propertyeval_minimum_nights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyeval',
            name='reviews_per_month',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
