# Generated by Django 4.2 on 2023-04-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertyeval_reviews_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyeval',
            name='reviews_per_month',
        ),
    ]
