# Generated by Django 4.2 on 2023-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='neighbourhood_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
