# Generated by Django 4.2 on 2023-05-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_neighbourhood_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['pk']},
        ),
    ]
