# Generated by Django 4.2 on 2023-05-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
